---
- hosts: localhost
  connection: local
  vars_files:
    - vars/vsphere-homelab.yml
  tasks:
    - block:
        - name: Continue Openshift Install
          include_role: name=continue-install-process