---
- hosts: localhost
  connection: local
  vars_files:
    - vars/vsphere-homelab.yml
  tasks:
    - block:
      - name: Create temporary directory
        tempfile:
          state: directory
        register: _tmpdir
      - set_fact:
          tmpdir: "{{ _tmpdir.path }}"
      - name: Download the openshift 4 client 
        unarchive:
          src: "{{ openshift_client_url }}"
          dest: "{{ tmpdir }}"
          remote_src: yes
      - name: Move oc client to /usr/local/bin
        shell: "mv {{ tmpdir }}/oc /usr/local/bin/oc"
      - name: Move kubectl client to /usr/local/bin
        shell: "mv {{ tmpdir }}/kubectl /usr/local/bin/kubectl"