---
- hosts: localhost
  connection: local
  vars_files:
    - vars/vsphere-temp.yml
  tasks:
    - name: Power On VMS
      shell: "govc vm.power -on -wait=true {{ item.name }}"
      with_items: "{{ machines }}"