---
- hosts: localhost
  connection: local
  vars_files:
    - vars/vsphere-homelab.yml
  tasks:
    - name: Power Off VMS
      shell: "govc vm.power -off -wait=true {{ item.name }}"
      with_items: "{{ machines }}"