---
- block:
  - include: setup.yml
  - name: Create PV yaml from template
    template:
      src: ../templates/registry-pv.yaml.j2
      dest: "{{ tmpdir }}/registry-pv.yaml"
  - name: Create Registry PV
    shell: >
      oc create -f {{ tmpdir }}/registry-pv.yaml
    
    #https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#registry-configuring-storage-vsphere_installing-vsphere
  - name: Patch the registry storage to make it create a PVC
    shell: >
      oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":}}}}'